language: node_js
node_js: stable
addons:
  firefox: latest
script:
- npm run test:lint
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    wct --npm --skip-plugin local || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    xvfb-run wct --npm --skip-plugin sauce || travis_terminate 1;
  fi
- |
  if [ "$TRAVIS_BRANCH" == "master" ] && [ $TRAVIS_PULL_REQUEST == false ]; then
    echo "Not a Pull Request and on branch master so bumping version";
    frauci-update-version;
    export TRAVIS_TAG=$(frauci-get-version)
  fi
deploy:
  provider: releases
  api_key: "$GITHUB_RELEASE_TOKEN"
  on:
    tags: true
env:
  global:
  - OWNER_NAME=Brightspace
  - REPO_NAME=d2l-fetch
  # SAUCE_USERNAME
  - secure: 9NEfhUpW6pf647+Yx0a1hztJlJUVjgsm+gxnwtcF2e+5bhJPrX8c6yL6YSLwatI+ZUWdX39D2K+AXA8Vt/dCyx6KXTxUYLIKu/sfu21RpfArt9XLei+ykc9EM3pWaYA1vZ36LVhoh+7Yw7/hHhPeANUbn9cgl7yfxvDxJpObom02E51IaFgfPYEK9gmeBgbnMHCAJfY1dUEVI6RQ7yg7RtRaGXjd5hDG0Z5BGhyBgdIfmONx1bSvh0ULlyj0a0SZvooi7VrniNU94iZCKNv814PZIA/HnfwbtorRXLQgOLIjLZAQewJ3bzv1xJYqNnK+z/W7b13T2Q+nvTBC8OeYAd4RubZkaZYjrnlZGYB22FWGnsNY61S3A66tAXZTIiOK3iXy/uR7tZvLxIBRa5fU2RBzAMxTNfE1CYRzgujxSFrgGzsw1Yjq21hbIkEzSLx+E1P4HBCmfX+qgcWsqgKruZ57OHKGhtB2D3tLVbEOnVwyAEB6z2BvpLurGWD6DRmJ8aUzUMOGY8kxWIKnqGf6eUSOpDJXyFSIch4EJvrVrzGNyOWok+bqzfDl4h6RdBASG8NafGtlXLRpBUReL8nQzwsHg6OYtOG8PYBNBbBuDGCdLKOIrda1nf+QCkV6hc81PExdGyiXFJ+ES0yPi6E5D7lp66g+wE/5gN9uafV2U5A=
  # SAUCE_ACCESS_KEY
  - secure: kLaCeUCbChOh/PjvINbhcVp3Hnf6t9dyn1/QPqWhfjs4Pr4GnYrGb8+VC6hkLXvlfeKObtEovDc8swDxFBr2iAVEklguYyRo+l+O3DcSStoOWhnpQ2dk5oZEDkpEvLSEly6Fh6z9hM8I4r7T+fCp+3ftJ7E/f4gvqh/x424t9KGbsM6PMPBDeWRS8cVKniSDBIGdQ2IS/Dnn1P6nfP1XZ5+9+aJBkKJO8348bMpNLfrjTgHtiwrcLtR8DfXwk4LG+OCNh63dP4QLCGlwjrPyFXxgrHsYHIQVXWZm8I0EnYvcXX9tdlTODe7/QnoOATFCxAxIGrmEbWP/SYQwl0Z4jyGu55X82LYnuY2UeypZvbQwFFOs0mpa7gbwtLcvKh87yGawqSHbImxHfA/8oQdkIWr4oFdxVklLIAhQzfO8cDunrwa/yTqPUCn36o6GaOfB8yb0lfImZ+UpKgR8yXnHNTNH45ooyaYuc3BTeKZUSshkV5yuTacM2f68HHXA2cYPlPrLtrAbr88pjzZNTqGl0OIR7JQkuPxnbpMPOkQeyAq8ZXmFbVGhMVUr+HLqkdBGtfS445fi86vYSggxpsvysv78lnO0wCG5zdwQta0cY0OYL9zo7l/BW9cJl2yQyxXxm45+nbjogcI/Q0Nj0+I0aGwTIpxfOCjaILYY4qq/JrI=
  # CDN_SECRET
  - secure: Dk/NWPv1jRZ7CdXi8jP6MrhXryiXRnrbGpVUP9Wq3wxEYkqESRhe5G0uDe9+6ixp5f5pxdWNoLkz3g3ZeADjGXqkFRhZ42MQca4YZgO3hc8+fXkop2pKlmrcsWCiw7k8EjqNxStOCkKSoc1Xn8OWc2YNJqSvD5XgKM2QJLknE4j45dYtAsy27p3OIqqg+L6hOMxC9G/sENXSvzd063Ud0SHAFKL6RlBhIjkRqxRR/kl14i+gmqAUQUA6FC5XWV98nBP1I+Bg2e5owEpvGIEVw03C9FK/y1kBl98/CXNMjPBgOitKBy7O6zzoWuRB4eQ5Ghe4JABQlrGaHHx9Fe17YkziNfBziXjCU2ManG8i4vSBMSfa+gZh/u29pbxG5WAChBXlPevR0Lq3JZAwGbN5ZoITMj+xqJ+vTBNCrl+QGRvcbBRnZc0qnjkDk05Rqxqgv0qWSVstJRDa0C2QqgYYy9OANpGQtqmMU0lYSjfRz+6QFZzMSriP8vmlHWbWm1i8CTsyEd2DjElG+sUEX7usoivbG6HsAcED+JstTq5cvTXF1vlEPvJOCvB8Zc2I0XfUuOuvUA8b65PpzhhPRwC2M4Ov/b04uniKv63bF2FhH9fbWoYSs8+DswpUqAhT5sGJaFsYk8GxtrP/I0P/itYWhDlkpyEa+7JSnJR2KOAIuoY=
  # GITHUB_RELEASE_TOKEN
  - secure: IgNPHGS2aBYYsK0uaCl0i3edHZscp5gO057y7UYC57mSRU63mylsvwhsm/gx+X+71sVCUHb7+su8trjY0I7A5v7GpBQgBqZodIauRMrY7JfOwtPp8qGMWEn6xkF1sTSdVTNSt59phn1L3UGtx3EIOQ0C5U5CvX1XOC+XO1xTXKBy6Dzyib8YJCUd/rQoeID8bdAJiJk3cqefnuW5u/ecAc8xSenva+fTTvAx34PeaSIVK4SaGnITRlYl56WZtrCRyuglqwwra4ck6lQhUyZhSN3oKB6Rpu9r5Q4iAZaG2RFDOT44MviWnmm+xFKMED3sS7gg7pHJWd0+MS6my4y5wrjtjtCkUWbDLE2PNwi+ou3m2QSz5humakHCapC6FWJUJuKWwOo146R06YVUdYyy88yFTnvSC7WPfvQcYxWVFSAv0s4QqVUWYmM7hKOR5CzUMUxfLczfEL8BB2wo0xIHWKJhY8BBpkY9gRvifT8+ZkGRmhtZfmQ2nyucYxXJKZenvBocL0IGAPiALSIHmCkk1w5zjV+9FtDxAxu9XG5oBq7xMiLRMyKrsqHSyJSD4BPc9HLJ8RFx+tJnpyIwxOQHI+Row45K72l3TZp0YhFe04xCNHpjSYIHF+HoAx4edo+uCnl1HuyG75To6csa2rtAiAVO6wJHowZPHypMmyHB9sU=
